#!/usr/bin/env bash
#
# Copies the standalone AinkradPluginTemplate — the canonical template — into
# Sources/ainkrad/Resources/Template, the copy `ainkrad new` scaffolds from.
#
#   scripts/sync-template.sh [template-repo] [ref]
#     template-repo  a local AinkradPluginTemplate clone
#                    (default: ../AinkradPluginTemplate beside this repo)
#     ref            the commit to copy (default: origin/development)
#
# Only one scaffolder token is rewritten: the AinkradAppKit `revision:` pin in
# project.yml becomes `TemplateScaffolder.templateSDKRevision`, because
# `ainkrad new` must stamp the CLI's OWN pin, not whatever the template pins.
# Every other token (`TemplatePlugin`, `TemplateFeature`, `MyApp`, `myplugin`,
# the API-version plist line, ...) is already in the template verbatim.
#
# Also writes scripts/template-manifest.sha256 — the standalone files' hashes
# at that commit — which TemplateParityTests checks the embedded copy against.
# Never edit Resources/Template by hand: change the template, then re-run this.
set -euo pipefail

PLACEHOLDER=60036ad9abe5d0ca4e84109bcc78a51f7b8578f0

kit=$(git rev-parse --show-toplevel)
src=${1:-"$kit/../AinkradPluginTemplate"}
ref=${2:-origin/development}
dest="$kit/Sources/ainkrad/Resources/Template"
manifest="$kit/scripts/template-manifest.sha256"

commit=$(git -C "$src" rev-parse --verify "$ref^{commit}")
stage=$(mktemp -d)
trap 'rm -rf "$stage"' EXIT

git -C "$src" archive "$commit" | tar -x -C "$stage"

pin=$(grep -oE '^    revision: [0-9a-f]{40}$' "$stage/project.yml" | awk '{print $2}')
[ "$(printf '%s\n' "$pin" | grep -c .)" = 1 ] || {
  echo "sync-template: expected exactly one AinkradAppKit revision pin in project.yml" >&2
  exit 1
}

{
  echo "# Generated by scripts/sync-template.sh — do not edit."
  echo "# source $commit"
  echo "# pin $pin"
  (cd "$stage" && find . -type f | sed 's|^\./||' | LC_ALL=C sort | while IFS= read -r f; do
    shasum -a 256 "$f"
  done)
} >"$manifest"

sed -i '' "s/^    revision: $pin\$/    revision: $PLACEHOLDER/" "$stage/project.yml"

rm -rf "$dest"
mkdir -p "$dest"
cp -Rp "$stage/." "$dest/"

echo "sync-template: Resources/Template <- AinkradPluginTemplate ${commit:0:7} (pin ${pin:0:7} -> placeholder)"
